#.github/workflows/dialyzer.yml

name: Dialyzer

on: pull_request

jobs:
  check_security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.14.1"]
        otp: ["25.0.4"]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v3
        id: mix-dialyzer-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}-{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-dialyzer-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Dialyzer
        run: mix dialyzer
